#!/bin/bash

#SBATCH -J score
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -c 24
#SBATCH --mem=500G
#SBATCH --output=logs/slurm-%A.out
#SBATCH --error=logs/slurm-%A.err

. /prj/TRR319_RMaP_BaseCalling_RNA004/Etienne/venv/mpi/bin/activate

PARENT=/prj/Schragi_Schwartz/analysis
INPUT=${PARENT}/data/modkit
OUTPUT=${PARENT}/results

CONTROL=${INPUT}/ctrl_1.bam.slim.tab.gz
CONDITION=${INPUT}/triple_1.bam.slim.tab.gz

./score_signatures_v3.py --n-jobs 24 --no-header --c2u-mode window --motif-mode YC --min-qual 25 --name "win_yc_25" --control $CONTROL --condition $CONDITION --output $OUTPUT
