# ********************
# I/O - absolute paths
# ********************

# path to annotations
INDEXLOC=/biodb/genomes/homo_sapiens/GRCh38_102
# name of GTF file
GTF=GRCh38.102.gtf
# name of FASTA file - uncompressed
FASTA=GRCh38_102.fa

# *******************
# program option call
# *******************

# modkit
MODKIT_BINARY=/biosw/modkit/0.6.1/bin/modkit

# extract calls
# default -q 1000 --ignore-index
# default --mapped-only and enforce filters (pass threshold value, skip inferred)
XCALLS_THRESH=--filter-threshold 0.5 --mod-threshold a:0.5 --mod-threshold 17596:0.5 --mod-threshold 69426:0.5 --mod-threshold 17802:0.5 --mod-threshold 19227:0.5 --mod-threshold m:0.5 --mod-threshold 19228:0.5 --mod-threshold 19229:0.5
XCALLS_OPTS=$(XCALLS_THRESH) --reference $(INDEXLOC)/$(FASTA)
# extract selected calls (a and 17802, motif-filtered)
# default -q 1000 --ignore-index
# default --mapped-only and enforce selected filters (skip inferred)
XCALLS_SELECTED_THRESH=--filter-threshold 0.5 --mod-threshold a:0.5 --mod-threshold 17802:0.5
XCALLS_SELECTED_OPTS=$(XCALLS_SELECTED_THRESH) --reference $(INDEXLOC)/$(FASTA)

# *******************
# downstream analyses
# *******************

# 27.04.26 add homotypic
COOC_OPTS=--plot-name dflt --codes a a
# COOC_OPTS=--plot-name dflt --codes 17802 17802


